version: '3'

services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: ${DB_PASS}
  web:
    build:
      context: .
      dockerfile: ./app/Dockerfile
    command: pipenv run python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./app/:/code/
    ports:
      - "8000:8000"
    environment:
      DB_PASS: ${DB_PASS}
      DB_HOST: db
      APP_LIST: ${APP_LIST}
      EMAIL_HOST_USER: ${EMAIL_HOST_USER}
      EMAIL_HOST_PASSWORD: ${EMAIL_HOST_PASSWORD}
    depends_on:
      - db
